name: milkman_interview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  easy_container: ^1.0.3
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.2.0+1
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/